# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-28 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cab',
            name='status',
            field=models.CharField(choices=[('b', 'already booked'), ('u', 'temporary unavailable'), ('a_s', 'available for booking for share'), ('a_s', 'available for booking for single')], max_length=65),
        ),
        migrations.AlterField(
            model_name='ride',
            name='type',
            field=models.CharField(choices=[('s', 'SHARING'), ('n', 'NOT SHARING')], max_length=255, unique=True),
        ),
    ]
