# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-28 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cab',
            name='status',
            field=models.CharField(choices=[('b', 'already booked'), ('u', 'temporary unavailable'), ('a', 'available for booking')], max_length=65),
        ),
        migrations.AlterField(
            model_name='location',
            name='type',
            field=models.CharField(choices=[('s', 'from'), ('d', 'to')], max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('c', 'COMPLETED'), ('b', 'BOOKED'), ('c_u', 'CANCELED_BY_USER'), ('c_d', 'CANCELED BY DRIVERER'), ('i', 'IN PROGRESS')], max_length=255, unique=True),
        ),
    ]
