# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-28 12:59
from __future__ import unicode_literals

import CAB.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CAB', '0002_auto_20181028_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=CAB.models.content_file_name)),
                ('pan_card', models.FileField(blank=True, max_length=500, null=True, upload_to=CAB.models.content_file_name)),
                ('license', models.FileField(blank=True, max_length=500, null=True, upload_to=CAB.models.content_file_name)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='license',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pan_card',
        ),
    ]
