# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-28 22:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAB', '0002_auto_20181028_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='passenger',
        ),
        migrations.AddField(
            model_name='ride',
            name='passenger',
            field=models.ManyToManyField(related_name='rides_passengers', to=settings.AUTH_USER_MODEL),
        ),
    ]
